[profile.default]
src = "src"
out = "out"
libs = ["lib"]
env_path = ".env"

remappings = ["@uniswap/v2-periphery/contracts=lib/v2-periphery/contracts","@uniswap/v2-core/contracts=lib/v2-core/contracts","@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/"]

[rpc_endpoints]
sepolia="https://eth-sepolia.g.alchemy.com/v2/G4mBTQkil8YSCbr0acyhwhERxiELhfRh"